### ISSUE TITLE
Refactor crawling to retrieve several elements at once

### ISSUE THREAD

**Issue by istvanrath** [IncQueryLabs/repo-crawler#1]
TWC provides a method to download elements at once. Issue POST request to /elements, i.e., /osmc/resources/<resourceID>/revisions/<revisionno>/elements, /osmc/resources/<resourceID>/branches/<branchId>/elements. The request body is a list of UUID separated by commas, e.g., 4eeb2e6d-9cbc-4f59-9d74-69263e52ba54,520bc74d-b5b4-40d5-87cb-9d0b8aba5d2e,7a057ae7-6281-462d-9dcd-de9931633f5c and the Content-Type in the request header should be “text/plain”.

**Comment by abelhegedus** [comment]
POST request tested and works, returning the requested elements as a JSON object with each requested object contents available as the value under the element ID key.

**Comment by abelhegedus** [comment]
Preliminary results when requesting all elements on a given depth in the tree:
```
Total: 103/82/1 query/response/sec | Now: 82 elem | AvgSpeed: 82 elem/sec
Total: 2898/1704/2 query/response/sec | Now: 1622 elem | AvgSpeed: 852 elem/sec
Total: 6948/4170/3 query/response/sec | Now: 2466 elem | AvgSpeed: 1390 elem/sec
Total: 8564/8564/4 query/response/sec | Now: 4394 elem | AvgSpeed: 2141 elem/sec
```
